post/urls.py
from django.urls import path
from .views import post_detail,PostList,Home,post_detail,deletepost,Post_Like


from .api import postListApi,postDetailApi,CommentListApi


app_name='post'
urlpatterns = [
    path('',Home,name='home'),
    path('add',PostList,name='post_list'),
    path('<slug:slug>/post_detail',post_detail, name='post_detail'),
    path('<slug:slug>/delete_post',deletepost, name='delete'),
    path('<slug:slug>/like',Post_Like, name='Post_Like'),
    
    
    
    #API
    path('api',postListApi.as_view(),name='post_list'),
    path('<slug:slug>/api_detail',postDetailApi.as_view(),name='postapi_detail'),
    path('api/comment',CommentListApi.as_view()),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('allposts/',include('post.urls',namespace='all_posts')),
    path('api-auth/', include('rest_framework.urls')),
  
]



urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/models.py
from django.db import models
from django .utils.text import slugify
from django.contrib.auth.models import User








class Post(models.Model):
    
    title=models.CharField(max_length=20)
    description=models.TextField(max_length=100000)
    image=models.ImageField(null=True,blank=True)
    tags=models.CharField(max_length=10)
    craete_date=models.DateTimeField
 

    def __str__(self):
        return self.title


    def save(self, *args, **kwargs):
       self.slug=slugify(self.title)
       super(Post, self).save(*args, **kwargs)
       
       
     
    
   
    
    

   






class Comment(models.Model):
    mypost = models.ForeignKey(Post,related_name='comments',on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    body = models.TextField(max_length=200)
    created_on = models.DateTimeField(auto_now_add=True)
    
    

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return self.name

# Create your models here.

post/forms.py
from .models import Comment,Post
from django import forms

class PostForm(forms.ModelForm):
     class Meta:
        model=Post
        fields=('title','description')
        



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name',  'body')

post/views.py
from django.shortcuts import render,redirect
from .models import Post,Comment
from .forms import CommentForm,PostForm
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib import messages


def Post_Like(request,slug):
    post=Post.objects.get(slug = slug)
    if request.method=='POST':
        if request.user in post.like.all():
            post.like.remove(request.user)
            is_like=False
        else:
            post.like.add(request.user)
            is_like=True
    post=Post.objects.get(slug = slug)
    html=render_to_string('include/likeform.html',{'post':post})
    return JsonResponse({'result':html})









def Home(request):
    home=Post.objects.all()
    return render(request,'base.html',{'home':home})
    



def PostList(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            myform=form.save(commit=False)
            myform.save()
            
            
            
                
    else:
        form = PostForm()
    return render(request, 'post.html', {'form': form})






        
def deletepost(request,slug):
    deleted=Post.objects.get(slug=slug)
    deleted.delete()
    return redirect('/allposts/')




def post_detail(request, slug):
    post=Post.objects.get(slug = slug)
    comment_1 = Comment.objects.all().filter(mypost = post)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            myform=form.save(commit=False)
            myform.user=request.user
            myform.mypost = post
            myform.save()
            
            
            comment_1 = Comment.objects.all().filter(mypost = post)
            html=render_to_string('include/comment.html',{'comment_1':comment_1})
            return JsonResponse({'result':html})
            
            

    else:
        form=CommentForm()
    
    return render(request , 'post_detail.html' , {'post':post , 'form':form ,'comment_1':comment_1  })
            
           



    def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            context["comment_1"] = Comment.objects.filter(mypost = self.get_object())
            return context
        
        

        
    
    
        

    














  
# Create your views here.

post/templates/base.html
<div class="row">


    <form method="POST" action="{% url 'all_posts:post_list' %}">
        {% csrf_token %}
        {{form}}
    <input style="height:40px ; width: 120px;" type="submit" value="Create Post">
    </form>
    
    {% for item in home %}
    
        <a href="{% url 'all_posts:post_detail' item.slug %}" >  
            <h1>  {{item.title}}  </h1>    
        </a>

       

        <p> {{item.description|truncatewords:"50"}}</p>
       
    {% endfor %}

   

</div>

post/templates/include/comment.html
{% for comment in comment_1 %}
							<div class="card-body">
								<div> 
									<h4 class=""> Date: {{comment.created_on}}</h4>
									<h4> Name: {{comment.name}} </h4>
									<h4 class=""> Comment: {{comment.body}}</h4>
									<hr>
								</div>
							</div>
{% endfor %}

post/templates/include/likeform.html
<form id="likepost" action=" {% url 'all_posts:Post_Like' post.slug %} "  method="POST">
    {% csrf_token %}
        <button type="submit"  > {%  if request.user in post.like.all %}DisLike{%else%}Like{%endif%} </button>
        <h3> ({{post.like.all|length}}) LIKE </h3>
            
</form>

post/templates/post.html
<div class='row'> 

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <h4> Title {{form.title}}</h4>
    <h4>Create Post</h4>
    <h4> {{form.description|truncatewords:"50"}}</h4>
     <input style="height:40px ; width: 120px;" type="submit" value="Add Post"> 
    

     
</form>




 <form method='POST'  action="{% url 'all_posts:home'%}"> <input style="height:40px ; width: 120px;" type="submit" value=" Show All Post"> {% csrf_token %}     </form>    </div>

post/templates/post_detail.html
<div class="row">

	<form   action="{% url 'all_posts:home'%}"> <input style="height:40px ; width: 120px;" type="submit" value="All Post">  </form>  	
		{% csrf_token %}
		<a href="{% url 'all_posts:delete' post.slug %}" >Delete Post

		</a>
				<ul>
					<i> <h1>
							{{post.title}}
						</h1> 
					</i>
					<i> <p> {{post.description}}</p> </i>
				</ul>
				
	

		


</div>




<div class="row"> 


			<div  class="product-details-frame">
				<div id="likeform1"> 
					
					{% include 'include/likeform.html' %} 
					
				</div>
					 
				<h3> ({{post.comments.all|length}}) comments </h3>
				<div class="card"  id = "add-all">
					{% include 'include/comment.html' %}

		
					
				</div>
					
					       <h3 class="frame-title">Add Your Comment</h3>
					       <form  method = "POST"  action= " {% url 'all_posts:post_detail' post.slug %} " id = "commentForm"  enctype="multipart/form-data" >
    							{% csrf_token %}
									
									<p> Enter Your Name	{{form.name}} </p>
									<h3>Enter Your Comment</h3>
									<h4 name="body">	{{form.body}} </h4>
						
     								<button style="height:40px ; width: 200px;" type="submit" class="btn btn-primary  m-3 " > Drop Your Comment </button>
									
    
							


								
					 	

			</div>

							</form>


				



		</div>





<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js" integrity="sha512-STof4xm1wgkfm7heWqFJVn58Hm3EtS31XFaagaa8VMReCXAkQnJZ+jEy8PCC/iT18dFy95WcExNHFTqLyp72eQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>
	$(document).ready(function(e){
		$(document).on('submit','#commentForm',function(e){
			e.preventDefault();
			$.ajax({
				type:$(this).attr('method'),
				url:$(this).attr('action'),
				data:$(this).serialize(),
				dataType:'json',
				success:function(response){
					$('#add-all').html(response['result'])
					$("#commentForm").trigger('reset');
					
					

				},
				error:function(response){}



			})    
			                
		})
	
	})
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js" integrity="sha512-STof4xm1wgkfm7heWqFJVn58Hm3EtS31XFaagaa8VMReCXAkQnJZ+jEy8PCC/iT18dFy95WcExNHFTqLyp72eQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>
	$(document).ready(function(e){
		$(document).on('submit','#likepost',function(e){
			e.preventDefault();
			$.ajax({
				type:$(this).attr('method'),
				url:$(this).attr('action'),
				data:$(this).serialize(),
				dataType:'json',
				success:function(response){
					$('#likeform1').html(response['result'])
					
					
					
		
				},
				error:function(response){}



			})    
			                
		})
	
	})
</script>



</div>